<Project>
  <PropertyGroup>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <Version>0.1.0</Version>
    <AssemblyVersion>$(Version).0</AssemblyVersion>
    <FileVersion>$(AssemblyVersion)</FileVersion>
    <Authors>Tony Chemit</Authors>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
